language: ruby
rvm:
- 2.2
- 2.1
- 2.0
env:
  global:
    secure: sU2O8v6WShJUNQXxxMb2OhVYvoiI8IfJMFeLCzyT+NPjwmk1r/0oxRpFvGgSdQA1oXoakW5iKi1suhG/VbIn336ggFZHnQQo9WQNFprFLTQWzIMidXBo8/pxd7aOq6rYUXxuT69P4cp54dNlYtUFL5IVbD/gMhbMKNhgFKJZuB7vlLadkif0lTNinXL3Pzh1tVwZ4oWyTQ+Ma/HF5Ge0CDaCAlP+W7HWwesFtg8TDgDAhJXAqldxAWb4pj2eAtbBoICdO7bvVCiGlbCFw9reLkgtgUX3xePl0AYU7/TFrqlX/NkrfuT0ygqpdYeaEDXAPi+Zr0beyNbS1xRp/+qGarR2OfMvwsl8mXpsSthREkgqi7rEM2N5jArSLlmM/3+aPOD4uVmtH2Y9uCVixCYzLlYTbfMrJfTGL//M6y+G9eR3rTN+2PEhxiGhPRNplGBSwZfoIpM72+lvWlSVwfN7tVtBlh5ERWw9Df15y+fBSwzWqP9LH9EI7mHXsjuPnXcYtoX3ToeVcOScr+7HJNsrWBgwTlX3eTKZZKoUb+W/whteM0J5AUHCWZeDhfXK3S4mI0eJp82hTxJ+WCFGCbw8Z/aLgk96OnD07y+u1/kKZsGR27IL+QtixmeF2EGyW6t7ZDLOjbK+q6FNYCt0+tYcn5QGsfWXsxUeUXIhOqCGnzA=
